# Generated by Django 3.2.4 on 2021-06-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest',
            old_name='des',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='dest',
            old_name='image',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='dest',
            old_name='name',
            new_name='nameimg',
        ),
    ]
