# Generated by Django 3.2.4 on 2021-06-12 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0002_auto_20210610_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest',
            old_name='img',
            new_name='img1',
        ),
        migrations.RenameField(
            model_name='dest',
            old_name='nameimg',
            new_name='nameimg1',
        ),
        migrations.RemoveField(
            model_name='dest',
            name='desc',
        ),
    ]
