# Generated by Django 3.2.4 on 2021-06-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_auto_20210612_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dest',
            old_name='img1',
            new_name='img',
        ),
    ]
