# Generated by Django 3.2.4 on 2021-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0005_message_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img1',
            field=models.ImageField(default=1, upload_to='pic'),
            preserve_default=False,
        ),
    ]
