# Generated by Django 3.2.4 on 2021-06-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0006_message_img1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('number', models.IntegerField(max_length=12)),
                ('message', models.TextField()),
            ],
        ),
    ]
